/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.chortitzer.lab.semillas;

import com.chortitzer.lab.semillas.frames.FormCategorias;
import com.chortitzer.lab.semillas.frames.FormClientes;
import com.chortitzer.lab.semillas.frames.FormEspecies;
import com.chortitzer.lab.semillas.frames.FormInformes;
import com.chortitzer.lab.semillas.frames.FormMuestras;
import com.chortitzer.lab.semillas.frames.FormResultados;
import java.awt.BorderLayout;
import javax.swing.JInternalFrame;
import javax.swing.JPanel;
import javax.swing.UIManager;

/**
 *
 * @author Industria
 */
public class FormMdi extends javax.swing.JFrame {

    /**
     * Creates new form FormMdi
     */
    public FormMdi() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        mnuMain = new javax.swing.JMenu();
        mnuMuestras = new javax.swing.JMenuItem();
        mnuResultados = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mnuClientes = new javax.swing.JMenuItem();
        mnuCategorias = new javax.swing.JMenuItem();
        mnuEspecies = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        mnuInformes = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        exitMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        desktopPane.setBackground(new java.awt.Color(255, 255, 255));
        desktopPane.setMinimumSize(new java.awt.Dimension(500, 500));

        mnuMain.setMnemonic('f');
        mnuMain.setText("Menu");

        mnuMuestras.setMnemonic('s');
        mnuMuestras.setText("Muestras");
        mnuMuestras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuMuestrasActionPerformed(evt);
            }
        });
        mnuMain.add(mnuMuestras);

        mnuResultados.setMnemonic('a');
        mnuResultados.setText("Resultados");
        mnuResultados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuResultadosActionPerformed(evt);
            }
        });
        mnuMain.add(mnuResultados);
        mnuMain.add(jSeparator1);

        mnuClientes.setMnemonic('o');
        mnuClientes.setText("Clientes");
        mnuClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuClientesActionPerformed(evt);
            }
        });
        mnuMain.add(mnuClientes);

        mnuCategorias.setText("Categorias");
        mnuCategorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCategoriasActionPerformed(evt);
            }
        });
        mnuMain.add(mnuCategorias);

        mnuEspecies.setText("Especies");
        mnuEspecies.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuEspeciesActionPerformed(evt);
            }
        });
        mnuMain.add(mnuEspecies);
        mnuMain.add(jSeparator2);

        mnuInformes.setText("Informes");
        mnuInformes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuInformesActionPerformed(evt);
            }
        });
        mnuMain.add(mnuInformes);
        mnuMain.add(jSeparator3);

        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        mnuMain.add(exitMenuItem);

        menuBar.add(mnuMain);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 981, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 751, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void mnuEspeciesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuEspeciesActionPerformed
        FormEspecies formEspecies = new FormEspecies();
        addFrame(formEspecies, "Especies");
    }//GEN-LAST:event_mnuEspeciesActionPerformed

    private void mnuCategoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCategoriasActionPerformed
        FormCategorias formCategorias = new FormCategorias();
        addFrame(formCategorias, "Categorias");
    }//GEN-LAST:event_mnuCategoriasActionPerformed

    private void mnuClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuClientesActionPerformed
        FormClientes formClientes = new FormClientes();
        addFrame(formClientes, "Clientes");
    }//GEN-LAST:event_mnuClientesActionPerformed

    private void mnuResultadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuResultadosActionPerformed
        FormResultados formResultados = new FormResultados();
        addFrame(formResultados, "Resultados");
    }//GEN-LAST:event_mnuResultadosActionPerformed

    private void mnuMuestrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuMuestrasActionPerformed
        FormMuestras formMuestras = new FormMuestras();
        addFrame(formMuestras, "Muestras");
    }//GEN-LAST:event_mnuMuestrasActionPerformed

    private void mnuInformesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuInformesActionPerformed
        FormInformes formInformes = new FormInformes();
        addFrame(formInformes, "Informes");
    }//GEN-LAST:event_mnuInformesActionPerformed

    public void addFrame(JPanel panel, String title) {
        try {
            JInternalFrame[] children = desktopPane.getAllFrames();

//creating a new internal frame from the Panel passes as parameter
            JInternalFrame frame = new JInternalFrame(title, true, true, true, true);
            frame.add(panel, BorderLayout.CENTER);
            //frame.pack();
            for (JInternalFrame f : children) {
                if (f.getTitle().equals(frame.getTitle())) {
                    f.setSelected(true);
                    return;
                }
            }
            desktopPane.add(frame);
            frame.setVisible(true);
            frame.setMaximum(true);

//checking to see if the child form already exist
            /*
             }*/
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            /*for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
             System.out.println(info.getName());
             if ("Nimbus".equals(info.getName())) {
             javax.swing.UIManager.setLookAndFeel(info.getClassName());
             break;
             }*/
            UIManager.setLookAndFeel(javax.swing.UIManager.getSystemLookAndFeelClassName());
            UIManager.put("Button.defaultButtonFollowsFocus", Boolean.TRUE);

        } catch (Exception ex) {
            ex.printStackTrace();
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormMdi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem mnuCategorias;
    private javax.swing.JMenuItem mnuClientes;
    private javax.swing.JMenuItem mnuEspecies;
    private javax.swing.JMenuItem mnuInformes;
    private javax.swing.JMenu mnuMain;
    private javax.swing.JMenuItem mnuMuestras;
    private javax.swing.JMenuItem mnuResultados;
    // End of variables declaration//GEN-END:variables

}
